name: Sync Medium Posts

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday
  workflow_dispatch:

jobs:
  update-medium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: gem install rss

      - name: Import Medium posts
        run: ruby _scripts/fetch_medium.rb

      - name: Commit and push if changed
        run: |
          git config user.name "shiki65536"
          git config user.email "shiki65536@github.com"
          git add -A _medium
          if ! git diff --cached --quiet; then
            git commit -m "Update Medium posts"
            git push
          else
            echo "No changes"
          fi
